# Tema 2: Probabilidades

## Experimento Aleatorio

Proceso mediante el cual se obtiene resultados, los cuales no conocemos el resultado final.

## Espacio Muestral

$$\Omega$$

Es la colección de todos los resultados posibles de un experimento aleatorio.

Exp: Lanzar un dado y observar la cara superior, $\Omega=\{1,2 ,3 ,4 ,5 ,6\}$

Exp: Lanzar dos dados y observar las caras superiores de ambos dados, $\Omega= \{(1,1),(1,2),(1,3), (1,4),...,(6,6) \}$

$\Omega= \{(i,j); i=1:6,j=1:6  \}$

El tamaño del espacio muestral en este caso es de 36. $6*6=36$

El espacio muestral de un experimento, puede ser:

* Finito numerables  
* Infinito no numerables 
* Infinito numerables

Exp: Tiempo en el que una persona tarda en llegar a la U desde su casa (0, 60)

Ejercicios recomendados: Pg: 222. 1 al 8.

### Ejemplos de espacios muestrales

1. El experimento: determinar el sexo de un niño/a recién nacido.

$$\Omega=\{Femenino, Masculino \}$$

2. En una competencia de caballos, con 7 caballos, el experimento: ordenar todas las posibles llegadas de estos 7 caballos. (a,b,c,d,e,f,g)

$$\# \Omega= 7 ! = 7*6*5*4*3*2*1=5040$$

$$\Omega=\{\text{Todas las 7! permutaciones de } (a,b,c,d,e,f,g) \}$$

3. El experimento es medir el tiempo de vida de un componente electrónico de un aparato (horas).

$$\Omega=\{x: x \geq 0  \}$$

```{r}
plot(1:10,rep(0,10),type="b")
```


## Evento (E)

$$E \subset \Omega$$

### Ejemplos

1. Sea el evento E nace una niña, $E=\{Femenino \}$

2. Se lanza un dado, sea el evento $A$ sale par

$$A=\{2,4,6 \}$$

3, En el ejemplo de los caballos. Sea el evento $E$ el caballo $c$ gana la competencia.

$$\# E = 1 * 6*5*4*3*2*1=6!= 720$$

$$E = \{(c,a,b,d,e,f,g),(c,a,b,d,e,g,f),(c,f,b,d,e,a,g),\ldots \}$$

$$E = \{ \text{Son las permutaciones de 6! de tal forma que c es primero: } (a,b,d,e,f,g) \}$$

4. Se lanza dos dados y se suman ambas caras. Defina los eventos:

$$\Omega=\{2,3,4,5,6,7,8,9,10,11,12 \}$$

* la suma es par, $A=\{2,4,6,8,10,12 \}$
* la suma es múltiplo de 7 $B=\{7\}$
* la suma es 1, $C=\{\emptyset\}$

5. En el ejemplo del componente electrónico, sea el evento $E$ el componente dura al menos 5 horas.

$$E=\{x: x\geq 5 \}$$

6. En el ejemplo del componente electrónico, sea el evento $E$ el componente dura a lo sumo 5 horas.

$$E=\{x: x\leq 5 \}$$

## Operaciones con los eventos

Sean $A$, $B$ y $C$ eventos.

* Evento vacio $\emptyset$

* El complemento de un evento 

 $$A^c=\{ w \in \Omega \text{ pero no pertenecen a } A     \}$$

* La unión de eventos 

$$A \cup B = \{w \in \Omega: w \in A \text{ ó } w\in B \}$$

* La intersección de eventos

$$A \cap B= \{w \in \Omega: w \in A \text{ y } w \in B   \}$$

* Dos eventos son mutuamente excluyentes si:


$$A \cap B = \emptyset$$







