<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Tema 2: Probabilidades | Estadística I</title>
  <meta name="description" content="Este libro esta destinado a la materia de Estadística I de la carrera de Informática de la Universidad Mayor de San Andres." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Tema 2: Probabilidades | Estadística I" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este libro esta destinado a la materia de Estadística I de la carrera de Informática de la Universidad Mayor de San Andres." />
  <meta name="github-repo" content="alvarolimber/EST-133" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Tema 2: Probabilidades | Estadística I" />
  
  <meta name="twitter:description" content="Este libro esta destinado a la materia de Estadística I de la carrera de Informática de la Universidad Mayor de San Andres." />
  

<meta name="author" content="Alvaro Chirino Gutierrez" />


<meta name="date" content="2020-12-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tema-1-estadística-descriptiva.html"/>
<link rel="next" href="tema-3-variables-aleatorias.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#audiencia"><i class="fa fa-check"></i>Audiencia</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-acuerdos"><i class="fa fa-check"></i>Software y acuerdos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html"><i class="fa fa-check"></i><b>1</b> Tema 1: Estadística Descriptiva</a><ul>
<li class="chapter" data-level="1.1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#definición-de-la-estadística."><i class="fa fa-check"></i><b>1.1</b> Definición de la estadística.</a></li>
<li class="chapter" data-level="1.2" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#historia"><i class="fa fa-check"></i><b>1.2</b> Historia</a><ul>
<li class="chapter" data-level="1.2.1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#tarea-de-repaso."><i class="fa fa-check"></i><b>1.2.1</b> Tarea de repaso.</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#conceptos-importantes"><i class="fa fa-check"></i><b>1.3</b> Conceptos importantes</a><ul>
<li class="chapter" data-level="1.3.1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#población"><i class="fa fa-check"></i><b>1.3.1</b> Población</a></li>
<li class="chapter" data-level="1.3.2" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#variable"><i class="fa fa-check"></i><b>1.3.2</b> Variable</a></li>
<li class="chapter" data-level="1.3.3" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#cualitativos-cualidades"><i class="fa fa-check"></i><b>1.3.3</b> Cualitativos (cualidades)</a></li>
<li class="chapter" data-level="1.3.4" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#cuantitativos-cantidad"><i class="fa fa-check"></i><b>1.3.4</b> Cuantitativos (cantidad)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#ordenando-los-datos"><i class="fa fa-check"></i><b>1.4</b> Ordenando los datos</a></li>
<li class="chapter" data-level="1.5" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>1.5</b> Medidas de tendencia central</a><ul>
<li class="chapter" data-level="1.5.1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#moda-mo"><i class="fa fa-check"></i><b>1.5.1</b> Moda (Mo)</a></li>
<li class="chapter" data-level="1.5.2" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#mediana-me"><i class="fa fa-check"></i><b>1.5.2</b> Mediana (Me)</a></li>
<li class="chapter" data-level="1.5.3" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#media-promedio-media-aritmética"><i class="fa fa-check"></i><b>1.5.3</b> Media, Promedio, Media aritmética</a></li>
<li class="chapter" data-level="1.5.4" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#propiedades-de-la-media"><i class="fa fa-check"></i><b>1.5.4</b> Propiedades de la media</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>1.6</b> Medidas de dispersión</a><ul>
<li class="chapter" data-level="1.6.1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>1.6.1</b> Rango</a></li>
<li class="chapter" data-level="1.6.2" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#varianza-poblacional"><i class="fa fa-check"></i><b>1.6.2</b> Varianza poblacional</a></li>
<li class="chapter" data-level="1.6.3" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#varianza-muestral-cuasivarianza"><i class="fa fa-check"></i><b>1.6.3</b> Varianza muestral (cuasivarianza)</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#gráficos"><i class="fa fa-check"></i><b>1.7</b> Gráficos</a><ul>
<li class="chapter" data-level="1.7.1" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#boxplot-diagramas-de-caja"><i class="fa fa-check"></i><b>1.7.1</b> Boxplot (Diagramas de caja)</a></li>
<li class="chapter" data-level="1.7.2" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#histograma"><i class="fa fa-check"></i><b>1.7.2</b> Histograma</a></li>
<li class="chapter" data-level="1.7.3" data-path="tema-1-estadística-descriptiva.html"><a href="tema-1-estadística-descriptiva.html#densidad"><i class="fa fa-check"></i><b>1.7.3</b> Densidad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html"><i class="fa fa-check"></i><b>2</b> Tema 2: Probabilidades</a><ul>
<li class="chapter" data-level="2.1" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#introducción"><i class="fa fa-check"></i><b>2.1</b> Introducción</a></li>
<li class="chapter" data-level="2.2" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#experimento-aleatorio"><i class="fa fa-check"></i><b>2.2</b> Experimento Aleatorio</a><ul>
<li class="chapter" data-level="2.2.1" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#ejemplos"><i class="fa fa-check"></i><b>2.2.1</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#espacio-muestral"><i class="fa fa-check"></i><b>2.3</b> Espacio Muestral</a><ul>
<li class="chapter" data-level="2.3.1" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#ejemplos-1"><i class="fa fa-check"></i><b>2.3.1</b> Ejemplos</a></li>
<li class="chapter" data-level="2.3.2" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#otros-ejemplos"><i class="fa fa-check"></i><b>2.3.2</b> Otros ejemplos</a></li>
<li class="chapter" data-level="2.3.3" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#ejercicios"><i class="fa fa-check"></i><b>2.3.3</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#eventos-e"><i class="fa fa-check"></i><b>2.4</b> Eventos (E)</a><ul>
<li class="chapter" data-level="2.4.1" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#ejemplos-2"><i class="fa fa-check"></i><b>2.4.1</b> Ejemplos</a></li>
<li class="chapter" data-level="2.4.2" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#evento-simple"><i class="fa fa-check"></i><b>2.4.2</b> Evento simple</a></li>
<li class="chapter" data-level="2.4.3" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#operaciones-con-los-eventos"><i class="fa fa-check"></i><b>2.4.3</b> Operaciones con los eventos</a></li>
<li class="chapter" data-level="2.4.4" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#algunas-propiedades-sobre-las-operaciones-en-eventos"><i class="fa fa-check"></i><b>2.4.4</b> Algunas propiedades sobre las operaciones en eventos</a></li>
<li class="chapter" data-level="2.4.5" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#algebra-de-eventos"><i class="fa fa-check"></i><b>2.4.5</b> Algebra de Eventos</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#probabilidad"><i class="fa fa-check"></i><b>2.5</b> Probabilidad</a><ul>
<li class="chapter" data-level="2.5.1" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#probabilidad-de-un-evento"><i class="fa fa-check"></i><b>2.5.1</b> Probabilidad de un evento</a></li>
<li class="chapter" data-level="2.5.2" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#axíomas-básicos-de-la-probabilidad"><i class="fa fa-check"></i><b>2.5.2</b> Axíomas básicos de la probabilidad</a></li>
<li class="chapter" data-level="2.5.3" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#propiedades"><i class="fa fa-check"></i><b>2.5.3</b> Propiedades</a></li>
<li class="chapter" data-level="2.5.4" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#espacios-equiprobables"><i class="fa fa-check"></i><b>2.5.4</b> Espacios equiprobables</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#probabilidad-condicional"><i class="fa fa-check"></i><b>2.6</b> Probabilidad Condicional</a><ul>
<li class="chapter" data-level="2.6.1" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#regla-de-la-multiplicación"><i class="fa fa-check"></i><b>2.6.1</b> Regla de la multiplicación</a></li>
<li class="chapter" data-level="2.6.2" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#independencia-de-eventos"><i class="fa fa-check"></i><b>2.6.2</b> Independencia de Eventos</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#teorema-de-la-probabilidad-total"><i class="fa fa-check"></i><b>2.7</b> Teorema de la Probabilidad Total</a></li>
<li class="chapter" data-level="2.8" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#teorema-de-bayes"><i class="fa fa-check"></i><b>2.8</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="2.9" data-path="tema-2-probabilidades.html"><a href="tema-2-probabilidades.html#ejercicios."><i class="fa fa-check"></i><b>2.9</b> Ejercicios.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html"><i class="fa fa-check"></i><b>3</b> Tema 3: Variables aleatorias</a><ul>
<li class="chapter" data-level="3.1" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#introducción-a-variable-aleatoria"><i class="fa fa-check"></i><b>3.1</b> Introducción a variable aleatoria</a></li>
<li class="chapter" data-level="3.2" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#función-de-probabilidad-densidad"><i class="fa fa-check"></i><b>3.2</b> Función de probabilidad (densidad)</a></li>
<li class="chapter" data-level="3.3" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#función-de-distribución-acumulada"><i class="fa fa-check"></i><b>3.3</b> Función de distribución (acumulada)</a></li>
<li class="chapter" data-level="3.4" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#variables-aleatorias-discretas"><i class="fa fa-check"></i><b>3.4</b> Variables aleatorias discretas</a></li>
<li class="chapter" data-level="3.5" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#variables-aleatorias-continuas"><i class="fa fa-check"></i><b>3.5</b> Variables aleatorias continuas</a></li>
<li class="chapter" data-level="3.6" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#esperanza-matemática"><i class="fa fa-check"></i><b>3.6</b> Esperanza matemática</a><ul>
<li class="chapter" data-level="3.6.1" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#propiedades-1"><i class="fa fa-check"></i><b>3.6.1</b> Propiedades</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#varianza"><i class="fa fa-check"></i><b>3.7</b> Varianza</a><ul>
<li class="chapter" data-level="3.7.1" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#propiedades-2"><i class="fa fa-check"></i><b>3.7.1</b> Propiedades</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#teorema-de-markov"><i class="fa fa-check"></i><b>3.8</b> Teorema de Markov</a></li>
<li class="chapter" data-level="3.9" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#desigualdad-de-chebyshev"><i class="fa fa-check"></i><b>3.9</b> Desigualdad de Chebyshev</a></li>
<li class="chapter" data-level="3.10" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#función-generatriz-de-momentos"><i class="fa fa-check"></i><b>3.10</b> Función Generatriz de Momentos</a><ul>
<li class="chapter" data-level="3.10.1" data-path="tema-3-variables-aleatorias.html"><a href="tema-3-variables-aleatorias.html#definición"><i class="fa fa-check"></i><b>3.10.1</b> Definición</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html"><i class="fa fa-check"></i><b>4</b> Tema 4: Distribuciones Discretas</a><ul>
<li class="chapter" data-level="4.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#bernoulli"><i class="fa fa-check"></i><b>4.1</b> Bernoulli</a><ul>
<li class="chapter" data-level="4.1.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#usos-bernoulli"><i class="fa fa-check"></i><b>4.1.1</b> Usos Bernoulli</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#binomial"><i class="fa fa-check"></i><b>4.2</b> Binomial</a><ul>
<li class="chapter" data-level="4.2.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#usos-binomial"><i class="fa fa-check"></i><b>4.2.1</b> Usos Binomial</a></li>
<li class="chapter" data-level="4.2.2" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#ejemplos-3"><i class="fa fa-check"></i><b>4.2.2</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#geométrica"><i class="fa fa-check"></i><b>4.3</b> Geométrica</a><ul>
<li class="chapter" data-level="4.3.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#usos-geométrica"><i class="fa fa-check"></i><b>4.3.1</b> Usos Geométrica</a></li>
<li class="chapter" data-level="4.3.2" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#ejemplos-4"><i class="fa fa-check"></i><b>4.3.2</b> Ejemplos</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#binomial-negativa"><i class="fa fa-check"></i><b>4.4</b> Binomial Negativa</a><ul>
<li class="chapter" data-level="4.4.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#usos-binomial-negativa"><i class="fa fa-check"></i><b>4.4.1</b> Usos Binomial Negativa</a></li>
<li class="chapter" data-level="4.4.2" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#ejemplo"><i class="fa fa-check"></i><b>4.4.2</b> Ejemplo,</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#hipergeométrica"><i class="fa fa-check"></i><b>4.5</b> Hipergeométrica</a><ul>
<li class="chapter" data-level="4.5.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#usos-hipergeométrica"><i class="fa fa-check"></i><b>4.5.1</b> Usos Hipergeométrica</a></li>
<li class="chapter" data-level="4.5.2" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#ejemplo-1"><i class="fa fa-check"></i><b>4.5.2</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#poisson"><i class="fa fa-check"></i><b>4.6</b> Poisson</a><ul>
<li class="chapter" data-level="4.6.1" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#usos-poisson"><i class="fa fa-check"></i><b>4.6.1</b> Usos Poisson</a></li>
<li class="chapter" data-level="4.6.2" data-path="tema-4-distribuciones-discretas.html"><a href="tema-4-distribuciones-discretas.html#ejemplos-5"><i class="fa fa-check"></i><b>4.6.2</b> Ejemplos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html"><i class="fa fa-check"></i><b>5</b> Tema 5: Distribuciones Continuas</a><ul>
<li class="chapter" data-level="5.1" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#uniforme"><i class="fa fa-check"></i><b>5.1</b> Uniforme</a></li>
<li class="chapter" data-level="5.2" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#exponencial"><i class="fa fa-check"></i><b>5.2</b> Exponencial</a><ul>
<li class="chapter" data-level="5.2.1" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#ejercicios-1"><i class="fa fa-check"></i><b>5.2.1</b> Ejercicios,</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#distribución-gamma"><i class="fa fa-check"></i><b>5.3</b> Distribución Gamma</a></li>
<li class="chapter" data-level="5.4" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#normal"><i class="fa fa-check"></i><b>5.4</b> Normal</a><ul>
<li class="chapter" data-level="5.4.1" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#estandarización-de-las-variables-transformación"><i class="fa fa-check"></i><b>5.4.1</b> Estandarización de las variables (transformación)</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#normal-estándar"><i class="fa fa-check"></i><b>5.5</b> Normal Estándar</a><ul>
<li class="chapter" data-level="5.5.1" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#otros-ejemplos-1"><i class="fa fa-check"></i><b>5.5.1</b> Otros ejemplos</a></li>
<li class="chapter" data-level="5.5.2" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#otro-propiedad"><i class="fa fa-check"></i><b>5.5.2</b> Otro propiedad</a></li>
<li class="chapter" data-level="5.5.3" data-path="tema-5-distribuciones-continuas.html"><a href="tema-5-distribuciones-continuas.html#propiedades-sobre-la-normal"><i class="fa fa-check"></i><b>5.5.3</b> Propiedades sobre la normal</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tema-2-probabilidades" class="section level1">
<h1><span class="header-section-number">2</span> Tema 2: Probabilidades</h1>
<div id="introducción" class="section level2">
<h2><span class="header-section-number">2.1</span> Introducción</h2>
<ul>
<li>Sumerios y Asirios utilizaban un hueso extraído del talón de animales como ovejas, ciervos o caballos, denominado astrágalo o talus, que tallaban para que pudieran caer en cuatro posiciones distintas, por lo que son considerados como los precursores de los dados.</li>
</ul>
<p><img src="https://4.bp.blogspot.com/--r_DGwMZe7s/T1UAykRPhdI/AAAAAAAAABg/o6L7MfegFAU/s1600/tabas1.png" /></p>
<ul>
<li>Por su parte, los juegos con dados se practicaron ininterrumpidamente desde los tiempos del Imperio Romano hasta el Renacimiento, aunque no se conoce apenas las reglas con las que jugaban.</li>
</ul>
<p><img src="https://1.bp.blogspot.com/-9RsQskb05yU/XSIUhq6G_MI/AAAAAAAAE-k/jHBslVmDgf0bJ4OguVIv8sf49PqCCL5RACLcBGAs/s1600/juego%2Bde%2Bmesa.jpg" /></p>
<ul>
<li>Uno de estos juegos, denominado “hazard”, palabra que en inglés y francés significa riesgo o peligro, fue introducido en Europa con la Tercera Cruzada. Las raíces etimológicas del término provienen de la palabra árabe “al-azar”, que significa “dado”. Posteriormente, en el “Purgatorio” de Dante el término aparece ya como “azar”.</li>
</ul>
<p>La historia de la probabilidad comienza en el siglo XVII cuando Pierre Fermat y Blaise Pascal tratan de resolver algunos problemas relacionados con los juegos de azar. Aunque algunos marcan sus inicios cuando Cardano (jugador donde los haya) escribió sobre 1520 El Libro de los Juegos de Azar (aunque no fué publicado hasta más de un siglo después, sobre 1660) no es hasta dicha fecha que comienza a elaborarse una teoría aceptable sobre los juegos.</p>
<div class="figure">
<img src="https://www.biografiasyvidas.com/biografia/f/fotos/fermat.jpg" alt="" />
<p class="caption">Pierre Fermat</p>
</div>
<div class="figure">
<img src="https://www.biografiasyvidas.com/biografia/p/fotos/pascal_blaise_1.jpg" alt="" />
<p class="caption">Blaise Pascal</p>
</div>
<p>Durante el siglo XVIII, debido muy particularmente a la popularidad de los juegos de azar, el cálculo de probabilidades tuvo un notable desarrollo sobre la base de la anterior definición de probabilidad. Destacan en 1713 el teorema de Bernoulli y la distribución binomial, y en 1738 el primer caso particular estudiado por De Moivre, del teorema central del límite. En 1809 Gauss inició el estudio de la teoría de errores y en 1810 Laplace, que había considerado anteriormente el tema, completó el desarrollo de esta teoría. En 1812 Pierre Laplace publicó Théorie analytique des probabilités en el que expone un análisis matemático sobre los juegos de azar.</p>
<div class="figure">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Danielbernoulli.jpg/220px-Danielbernoulli.jpg" alt="" />
<p class="caption">Daniel Bernoulli</p>
</div>
<div class="figure">
<img src="https://estaticos.elperiodico.com/resources/jpg/2/5/johann-carl-friedrich-gauss-1525091415852.jpg" alt="" />
<p class="caption">Gauss</p>
</div>
<div class="figure">
<img src="https://historiaybiografias.com/archivos_varios5/laplace.jpg" alt="" />
<p class="caption">Pierre Laplace</p>
</div>
</div>
<div id="experimento-aleatorio" class="section level2">
<h2><span class="header-section-number">2.2</span> Experimento Aleatorio</h2>
<blockquote>
<p><strong>Definición de experimento:</strong> Proceso mediante el cual se obtiene un resultdo de una observación.</p>
</blockquote>
<blockquote>
<p><strong>Definición de experimento aleatorio:</strong> Cuando los resultados de la observacion no s epuede predecir con exactitud antes de realizar el experimento.</p>
</blockquote>
<div id="ejemplos" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Ejemplos</h3>
<ol style="list-style-type: decimal">
<li>Lanzar una moneda</li>
<li>Lanzar un dado, lanzar un tetraedro</li>
<li>Una competencia de 6 caballos, quien es el caballo ganador</li>
<li>Un partido de futbol entre el equipo A y el equipo B</li>
<li>El clima de mañana</li>
<li>El resultado de una votación con 3 candidatos</li>
<li>El tiempo de entrega de una pizza</li>
<li>El tiempo de atención en la caja recaudadora de la universidad en un dia particular</li>
</ol>
</div>
</div>
<div id="espacio-muestral" class="section level2">
<h2><span class="header-section-number">2.3</span> Espacio Muestral</h2>
<blockquote>
<p><strong>Definición de espacio muestral:</strong> Es la colección (conjunto) de todos los resultados posibles de un experimento aleatorio. Denotado por…</p>
</blockquote>
<p><span class="math display">\[\Omega\]</span></p>
<div id="ejemplos-1" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Ejemplos</h3>
<p>El espacio muestra de los anteriores ejemplos</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\Omega=\{Cara,Cruz\}\)</span></li>
<li><span class="math inline">\(\Omega=\{1,2,3,4,5,6\}\)</span>, para el tetraedro <span class="math inline">\(\Omega=\{1,2,3,4\}\)</span></li>
<li>Sean los caballos a,b,c,d,e y f, <span class="math inline">\(\Omega=\{a,b,c,d,e,f\}\)</span></li>
<li><span class="math inline">\(\Omega=\{ganaA, ganaB, empate\}\)</span></li>
<li><span class="math inline">\(\Omega=\{soleado, lluvia,nublado \}\)</span></li>
<li>Sean los candidatos x, y, z <span class="math inline">\(\Omega=\{x,y,z\}\)</span></li>
<li>Sea <span class="math inline">\(x\)</span> el tiempo, <span class="math inline">\(\Omega=\{x &gt; 0\}\)</span>
7a. Sea <span class="math inline">\(x\)</span> el tiempo en horas, <span class="math inline">\(\Omega=\{ 0&lt;x&lt;24 \}\)</span></li>
<li>Sea <span class="math inline">\(x\)</span> el tiempo en horas, <span class="math inline">\(\Omega=\{ 0&lt;x&lt;8 \}\)</span></li>
</ol>
<blockquote>
<p>Nota: el tamaño de <span class="math inline">\(\Omega\)</span> lo denotaremos por:</p>
</blockquote>
<p><span class="math display">\[\#\Omega\]</span></p>
<p>El espacio muestral de un experimento, puede ser:</p>
<ul>
<li>Finito numerables<br />
</li>
<li>Infinito no numerables</li>
<li>Infinito numerables
+ Los dias hasta que suceda un terremoto en la ciudad <span class="math inline">\(x\)</span></li>
</ul>
<p>Ejemplo, sean los siguientes experimentos aleatorios:</p>
<ul>
<li><p>El estado de animo de una persona. <span class="math inline">\(\Omega=\{feliz, triste, enojada, asustada, \ldots\}\)</span> es finito<br />
y es numerable. Donde <span class="math inline">\(\# \Omega=\)</span> la cantidad de estados de animo que definamos estudiar.</p></li>
<li><p>El número de veces necesario al lanzar una moneda hasta sacar cara. <span class="math inline">\(\Omega=\{1,2,3,4, \ldots, \infty \}\)</span> es infinito y numerable. <span class="math inline">\(\# \Omega=\infty\)</span>.</p></li>
<li><p>Duración de un artefacto electrónico. <span class="math inline">\(\Omega=\{w\in IR, w \geq 0 \}\)</span> es infinito y no numerable. <span class="math inline">\(\# \Omega=\infty\)</span>.</p></li>
</ul>
</div>
<div id="otros-ejemplos" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Otros ejemplos</h3>
<ol style="list-style-type: decimal">
<li>Exp: Lanzar dos dados y observar las caras superiores de ambos dados, <span class="math inline">\(\Omega= \{(1,1),(1,2),(1,3), (1,4),...,(6,6) \}\)</span>, <span class="math inline">\(\Omega= \{(i,j); i=1:6,j=1:6 \}\)</span>, <span class="math inline">\(\#\Omega=36\)</span></li>
<li>El experimento: determinar el sexo de un niño/a recién nacido. <span class="math inline">\(\Omega=\{Femenino, Masculino\}\)</span></li>
<li>En una competencia de caballos, con 7 caballos, el experimento: ordenar todas las posibles llegadas de estos 7 caballos. (a,b,c,d,e,f,g), <span class="math inline">\(\#\Omega=7!=5040\)</span></li>
</ol>
<p><span class="math display">\[\Omega=\{\text{Todas las 7! permutaciones de } (a,b,c,d,e,f,g) \}\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li>El experimento es medir el tiempo de vida de un componente electrónico de un aparato (horas).</li>
</ol>
<p><span class="math display">\[\Omega=\{x \in IR: x \geq 0  \}\]</span></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="tema-2-probabilidades.html#cb28-1"></a><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb28-2"><a href="tema-2-probabilidades.html#cb28-2"></a><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">10</span>),<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;t&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb28-3"><a href="tema-2-probabilidades.html#cb28-3"></a><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>,<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">10</span>),<span class="dt">type=</span><span class="st">&quot;b&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;t&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<ol start="5" style="list-style-type: decimal">
<li>El experimento es: Seleccionar 3 personas de un grupo de 50 personas, describir el espacio muestral y el tamaño de este.</li>
</ol>
<ul>
<li><span class="math inline">\(\# \Omega= C_3^{50}=\binom{50}{3}=19600\)</span></li>
<li><span class="math inline">\(\Omega=\{(i,j,k); i,j,k \in 1:50, i\neq j \neq k \}\)</span></li>
</ul>
</div>
<div id="ejercicios" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Ejercicios</h3>
<ol style="list-style-type: decimal">
<li>Cuatro profesores se distribuyen al azar en 4 oficinas numeradas del 1 al 4. Si los profesores pueden estar en la misma oficina. Describir <span class="math inline">\(\Omega\)</span></li>
</ol>
<p><span class="math display">\[\#\Omega=4!+4+4\binom{4}{2}+\binom{4}{2}\binom{4}{3}+\binom{4}{2}\binom{4}{2}\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Se lanza una moneda y un dado simultaneamente. Describir <span class="math inline">\(\Omega\)</span>, <span class="math inline">\(\#\Omega=12\)</span></li>
</ol>
<p><span class="math display">\[\Omega=\{(i,j); i=\{cruz,cara\},j=1:6 \}\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Cinco trabajadores, de los cuales 3 pertenecen a un grupo minoritario se asignan a 5 empleos netamente distintos. Describir <span class="math inline">\(\Omega\)</span>,</li>
</ol>
<ul>
<li><p>Ignorar al grupo minoritario, <span class="math inline">\(\# \Omega=5!\)</span>, sean los trabajdores a,b,c,d,e,f <span class="math inline">\(\Omega=\{5!; a,b,c,d,e\}\)</span></p></li>
<li><p>Solo con los 3 trabajadores minoritarios: Sea los trabajadores minoritarios <span class="math inline">\(a,b,c\)</span> y numerámos los empleos de <span class="math inline">\(1:5\)</span> <span class="math inline">\(\Omega=\{(a=i,b=j,c=k); i,j,k=1:5, i \neq j \neq k\}\)</span>, <span class="math inline">\(\# \Omega= CR_{5,3}=\binom{7}{3}=35\)</span></p></li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Dos personas A y B se distribuyen al azar en tres oficinas numeradas 1,2 y 3 .Si las dos personas pueden estar en la misma oficina ,defina un espacio muestral adecuado</li>
</ol>
<p><span class="math display">\[\Omega=\{(1A,1B),(2A,2B),(3A,3B),(1A,2B),(1A,3B),(2A,3B),(1B,2A),(1B,3A),(2B,3A) \}\]</span>
5. En un profesor toma un examen con 5 preguntas de falso/verdadero, describa el espacio muestral asociado a este experimento aleatorio, relacionado a las respuestas del estudiante.</p>
<p>Resp. <span class="math inline">\(\# \Omega=2*2*2*2*2=2^5=32\)</span>, <span class="math inline">\(\Omega=\{(VVVVV),(VFVFV),\ldots,(FFFFF)\}\)</span></p>
<ol start="6" style="list-style-type: decimal">
<li>En un profesor toma un examen con 5 preguntas de opción múltiple (5 opciones por pregunta, con una sola opción correcta), describa el espacio muestral asociado a este experimento aleatorio, relacionado a las respuestas del estudiante.</li>
</ol>
<p>Resp. $# =5<em>5</em>5<em>5</em>5=5^5=3125 $, Supongamos que las alternativas en las opciones son <span class="math inline">\((a,b,c,d,e)\)</span> <span class="math inline">\(\Omega=\{(aaaaa),(aaaab),\ldots ,(eeeee)\}\)</span></p>
</div>
</div>
<div id="eventos-e" class="section level2">
<h2><span class="header-section-number">2.4</span> Eventos (E)</h2>
<p>Sea <span class="math inline">\(E\)</span> un evento, este se define como:</p>
<p><span class="math display">\[E \subset \Omega\]</span></p>
<div id="ejemplos-2" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Ejemplos</h3>
<ol style="list-style-type: decimal">
<li><p>En el ejemplo del nacimiento de niños/as, el experimento trataba de determinar el sexo del niño/a. Sea el evento <span class="math inline">\(E\)</span> nace una niña, <span class="math inline">\(E=\{Femenino \}\)</span>, otro evento puede ser <span class="math inline">\(E2=\{masculino\}\)</span></p></li>
<li><p>Sea el experimento lanzar un dado (de 6 caras). Sean los eventos</p></li>
</ol>
<ul>
<li><span class="math inline">\(A\)</span> el resultado es par. <span class="math inline">\(A=\{2,4,6 \}\)</span></li>
<li><span class="math inline">\(B\)</span> el resultado es mayor a 5. <span class="math inline">\(B=\{6\}\)</span></li>
<li><span class="math inline">\(C\)</span> el resultado es un número primo. <span class="math inline">\(C=\{1,2,3,5\}\)</span>, <span class="math inline">\(C=\{2,3,5\}\)</span></li>
<li><span class="math inline">\(D\)</span> el resultado es mayor a 6. <span class="math inline">\(D=\emptyset\)</span></li>
<li><span class="math inline">\(E\)</span> el resultado mayor a 0. <span class="math inline">\(E=\Omega\)</span></li>
</ul>
<p>Nota: recordar que <span class="math inline">\(\emptyset \subset \Omega\)</span>, <span class="math inline">\(\Omega \subset \Omega\)</span>.</p>
<ol start="3" style="list-style-type: decimal">
<li>En una competencia de caballos, con 7 caballos, el experimento: ordenar todas las posibles llegadas de estos 7 caballos. <span class="math inline">\((a,b,c,d,e,f,g)\)</span>. Sea el evento <span class="math inline">\(E\)</span> el caballo <span class="math inline">\(c\)</span> gana la competencia, describa el evento o el tamaño de este evento.</li>
</ol>
<p>Recordar que <span class="math inline">\(\# \Omega= 7!\)</span></p>
<p><span class="math display">\[\# E = 1 * 6*5*4*3*2*1=6!= 720\]</span></p>
<p><span class="math display">\[E = \{(c,a,b,d,e,f,g),(c,a,b,d,e,g,f),(c,f,b,d,e,a,g),\ldots \}\]</span></p>
<p><span class="math display">\[E = \{ \text{Son las permutaciones de 6! de tal forma que c es primero: } (a,b,d,e,f,g) \}\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li>Se lanza dos dados y se suman ambas caras. Defina los eventos:</li>
</ol>
<p><span class="math display">\[\Omega=\{2,3,4,5,6,7,8,9,10,11,12 \}\]</span></p>
<ul>
<li>la suma es par, <span class="math inline">\(A=\{2,4,6,8,10,12 \}\)</span></li>
<li>la suma es múltiplo de 7 <span class="math inline">\(B=\{7\}\)</span></li>
<li>la suma es 1, <span class="math inline">\(C=\{\emptyset\}\)</span></li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>En el ejemplo del componente electrónico, sea el evento <span class="math inline">\(E\)</span> el componente dura al menos 5 horas.</li>
</ol>
<p><span class="math display">\[E=\{x: x\geq 5 \}\]</span></p>
<ol start="6" style="list-style-type: decimal">
<li>En el ejemplo del componente electrónico, sea el evento <span class="math inline">\(E\)</span> el componente dura a lo sumo 5 horas.</li>
</ol>
<p><span class="math display">\[E=\{x: x\leq 5 \}\]</span>
7. Una pareja inicia la planificación familiar, ellos quieren tener 4 hijos/as. Esta pareja esta interesada en los siguientes eventos:</p>
<ul>
<li><span class="math inline">\(A:\)</span> todos del mismo sexo</li>
<li><span class="math inline">\(B:\)</span> exactamente un varón</li>
<li><span class="math inline">\(C:\)</span> Por lo menos dos varones</li>
<li><span class="math inline">\(D:\)</span> exactamente 1 mujer</li>
</ul>
<p>Listar los elementos vinculados a estos eventos.</p>
<p>Solución,</p>
<p>El experimento aleatorio es: el sexo de los 4 hijos/hijas de esta pareja <span class="math inline">\((h1,h2,h3,h4)\)</span>. <span class="math inline">\(\# \Omega= 2*2*2*2=16\)</span></p>
<p>El espacio muestral es <span class="math inline">\(\Omega:\)</span></p>
<div class="line-block">(mmmm) | (hmmm) | (mhmm) | (mmhm) |<br />
(mmmh) | (hhmm) | (mhhm) | (hmhm) |<br />
(mhmh) | (hmmh) | (mmhh) | (hhhm) |<br />
(hhmh) | (hmhh) | (mhhh) | (hhhh) |</div>
<p>Ahora sobre los eventos:</p>
<ul>
<li><span class="math inline">\(A=\{(mmmm),(hhhh) \}\)</span>, <span class="math inline">\(\# A=2\)</span></li>
<li><span class="math inline">\(B=\{(hmmm),(mhmm),(mmhm),(mmmh) \}\)</span>, <span class="math inline">\(\# B=4\)</span></li>
<li><span class="math inline">\(C=\{ (hhmm),(mhhm),(hmhm),(mhmh),(hmmh),(mmhh),(hhhm),(hhmh),(hmhh),(mhhh),(hhhh)\}\)</span>, <span class="math inline">\(\# C= 11\)</span></li>
<li><span class="math inline">\(D=\{ (hhhm),(hhmh),(hmhh),(mhhh)\}\)</span></li>
</ul>
</div>
<div id="evento-simple" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Evento simple</h3>
<p>Un evento simple, es el elemento más pequeño (suelto) dentro de otro evento. También, un evento simple tiene correspondencia única con los posibles resultados de <span class="math inline">\(\Omega\)</span>.</p>
<p>Sea <span class="math inline">\(\Omega=\{w_1,w_2,\ldots,w_i,\ldots\}\)</span>, los resultados <span class="math inline">\(w_i\)</span> son conocidos como los eventos simple. En el fondo un evento es la colección de algunos eventos simples, según la definición del evento</p>
</div>
<div id="operaciones-con-los-eventos" class="section level3">
<h3><span class="header-section-number">2.4.3</span> Operaciones con los eventos</h3>
<p>Sean <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span> y <span class="math inline">\(C\)</span> eventos.</p>
<ul>
<li><p>Eventos simples: son eventos que contienen un solo elemento, tienen correspondencia con los resultados del espacio muestral. Sea <span class="math inline">\(w\)</span> un evento simple de un <span class="math inline">\(\Omega\)</span> “numerable”.</p></li>
<li><p>Evento vacio <span class="math inline">\(\emptyset\)</span></p></li>
<li><p>El complemento de un evento</p></li>
</ul>
<p><span class="math display">\[A^c=\{ w \in \Omega \wedge  w\notin  A\}\]</span></p>
<ul>
<li>La unión de eventos</li>
</ul>
<p><span class="math display">\[A \cup B = \{w \in \Omega: w \in A \text{ ó } w\in B \}\]</span></p>
<ul>
<li>La intersección de eventos</li>
</ul>
<p><span class="math display">\[A \cap B= \{w \in \Omega: w \in A \wedge w \in B   \}\]</span></p>
<ul>
<li>Dos eventos son mutuamente excluyentes (No tienen elementos en común) si:</li>
</ul>
<p><span class="math display">\[A \cap B = \emptyset\]</span>
* Inclusión de eventos</p>
<p><span class="math display">\[A \subset B =\{w \in \Omega : w \in A \rightarrow w \in B   \}\]</span></p>
<ul>
<li><p>Ejemplo: En el lanzamiento de 2 dados y la suma de sus resultados, sean los eventos</p></li>
<li><p><span class="math inline">\(A:\)</span> La suma es par</p></li>
<li><p><span class="math inline">\(B:\)</span> La suma es impar</p></li>
<li><p><span class="math inline">\(C:\)</span> La suma es un número primo</p></li>
<li><p><span class="math inline">\(D:\)</span> La suma es mayor a 3</p></li>
</ul>
<p>Describir los eventos y luego encontrar</p>
<ul>
<li>$A C={2,3,4,5,6,7,8,10,11,12} $</li>
<li><span class="math inline">\(B \cap D=\{5,7,9,11 \}\)</span></li>
<li><span class="math inline">\(C \cup D^c= D^c \subset C= C\)</span></li>
<li><span class="math inline">\(A \cap (B\cup C )=\)</span></li>
<li><span class="math inline">\(A \cup (B\cap C)=\)</span></li>
</ul>
<p>El espacio muestral <span class="math inline">\(\Omega=\{2,3,4,5,6,7,8,9,10,11,12\}\)</span></p>
<p>Los eventos</p>
<ul>
<li><p><span class="math inline">\(A=\{2,4,6,8,10,12\}\)</span></p></li>
<li><p><span class="math inline">\(B=\{3,5,7,9,11 \}\)</span></p></li>
<li><p><span class="math inline">\(C=\{2,3,5,7,11 \}\)</span></p></li>
<li><p><span class="math inline">\(D=\{4,5,6,7,8,9,10,11,12\}\)</span></p></li>
<li><p><span class="math inline">\(D^C=\{2,3\}\)</span></p></li>
<li><p><span class="math inline">\(C \subset B\)</span>, entonces <span class="math inline">\(C\cup B=B\)</span>, <span class="math inline">\(C \cap B=C\)</span></p></li>
</ul>
</div>
<div id="algunas-propiedades-sobre-las-operaciones-en-eventos" class="section level3">
<h3><span class="header-section-number">2.4.4</span> Algunas propiedades sobre las operaciones en eventos</h3>
<p>Sean <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span> y <span class="math inline">\(D\)</span> eventos,</p>
<ul>
<li><p><span class="math inline">\(A \cup B= B \cup A\)</span>, <span class="math inline">\(A \cap B= B \cap A\)</span> Conmutativa</p></li>
<li><p><span class="math inline">\((A \cup B) \cup C= A \cup (B \cup C)\)</span> , <span class="math inline">\((A \cap B) \cap C= A \cap (B \cap C)\)</span> Asociativa</p></li>
<li><p><span class="math inline">\(A \cup (B \cap C)= (A \cup B) \cap (A \cup C)\)</span> Distributiva</p></li>
<li><p>$A (B C)=(AB) (AC) $ Distributiva</p></li>
<li><p><span class="math inline">\((A \cup B)^c= A^c \cap B^c\)</span></p></li>
<li><p><span class="math inline">\((A \cap B)^c= A^c \cup B^c\)</span></p></li>
</ul>
<p>Ley de Morgan, sea <span class="math inline">\(E_1, E_2, E_3, \ldots, E_n\)</span>, <span class="math inline">\(n\)</span> eventos de algun experimento aleatorio</p>
<p><span class="math display">\[ (\cup_{i=1}^{n}\{E_i\})^c = \cap_{i=1}^{n}\{E_i ^c\}\]</span></p>
<p><span class="math display">\[ (\cap_{i=1}^{n}\{E_i\})^c = \cup_{i=1}^{n}\{E_i ^c\}\]</span></p>
<ul>
<li><span class="math inline">\((A^c)^c=A\)</span></li>
</ul>
</div>
<div id="algebra-de-eventos" class="section level3">
<h3><span class="header-section-number">2.4.5</span> Algebra de Eventos</h3>
<blockquote>
<p><strong>Definición:</strong> Sea <span class="math inline">\(A\)</span> un evento, Sea <span class="math inline">\(\Sigma\)</span> una clase de subconjuntos de <span class="math inline">\(\Omega\)</span></p>
</blockquote>
<p>Esta es un algebra de eventos si:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\Omega \in \Sigma\)</span></li>
<li>Si <span class="math inline">\(A\in \Sigma\Rightarrow A^C \in \Sigma\)</span></li>
<li>Si <span class="math inline">\(A,B \in \Sigma \Rightarrow A \cup B \in \Sigma\)</span></li>
</ol>
<p>Ejemplo: El experimento es lanzar un dado y observar el resultado de la cara <span class="math inline">\(\Omega=\{1,2,3,4,5,6\}\)</span>, <span class="math inline">\(\# \Omega=6\)</span>, <span class="math inline">\(\Omega \cup \emptyset=\Omega\)</span></p>
<p><span class="math display">\[\Sigma=\{\Omega,\emptyset \}\]</span>
Sera que la siguiente clase es un algebra de eventos:</p>
<p><span class="math display">\[\Sigma=\{\Omega, \emptyset, 1, (2,3,4,5,6) \}\]</span></p>
<p><span class="math display">\[\Sigma=\{\Omega, \emptyset, 1, (2,3,4,5,6), 2, (1,3,4,5,6),(1,2),(3,4,5,6) \}\]</span></p>
<blockquote>
<p>Nota: El algebra de eventos no es único</p>
</blockquote>
<p><strong>Definición:</strong> Se dice que <span class="math inline">\(\Sigma\)</span> es un <span class="math inline">\(\sigma-algebra\)</span></p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\Omega \in \Sigma\)</span></li>
<li>Si <span class="math inline">\(A\in \Sigma\Rightarrow A^C \in \Sigma\)</span></li>
<li>Si <span class="math inline">\(A_i \in \Sigma\)</span> para <span class="math inline">\(i=1,2, \ldots\)</span> <span class="math inline">\(\Rightarrow \cup_{i=1}^\infty A_i \in \Sigma\)</span></li>
</ol>
<p>Ejemplo: El experimento es lanzar un dado y observar el resultado de la cara <span class="math inline">\(\Omega=\{1,2,3,4,5,6\}\)</span>, <span class="math inline">\(\# \Omega=6\)</span>, <span class="math inline">\(\Omega \cup \emptyset=\Omega\)</span></p>
<p><span class="math display">\[\Sigma=\{\Omega,\emptyset \}\]</span></p>
<p><span class="math display">\[\Sigma=\{\Omega,\emptyset,1,(2,3,4,5,6) \}\]</span></p>
<p>Existe un <span class="math inline">\(\sigma -algebra\)</span> que contiene todas las combinaciones posibles contiene en particular todos los eventos simples de <span class="math inline">\(\Omega\)</span>.</p>
<p><span class="math display">\[\Sigma=\{\Omega,\emptyset,1,2,3,4,5,6,(2,3,4,5,6),(1,3,4,5,6),(1,2,4,5,6),(1,2,3,5,6),(1,2,3,4,6),(1,2,3,4,5),(1,2),(1,3),...,(1,2,3),(1,2,4),...(1,2,3,4),(1,2,3,5),...\}\]</span>
<span class="math display">\[\#\Sigma=2^{\# \Omega}\]</span></p>
<p><span class="math display">\[\#\Sigma=2^6=64\]</span></p>
<ul>
<li>Ejemplo al lanzar una moneda dos veces y observar los resultados <span class="math inline">\(\Omega=\{CC,SC,CS,SS\}\)</span> si armamos un <span class="math inline">\(\sigma-algebra\)</span> donde incluyamos todos los eventos simples, entonces, <span class="math inline">\(\#\Sigma=2^4=16\)</span>.</li>
</ul>
<p><span class="math display">\[\Sigma=\{\Omega,\emptyset,CC,SC,CS,SS,(CC,SC),(CC,CS),(CC,SS),(SC,CS),(SC,SS),(CS,SS),(CC,SC,CS),(CC,SC,SS),(CC,CS,SS),(SC,CS,SS)\}\]</span></p>
</div>
</div>
<div id="probabilidad" class="section level2">
<h2><span class="header-section-number">2.5</span> Probabilidad</h2>
<blockquote>
<p>Medida de incertidumbre entre 0 y 1 asociado a un experimento aleatorio</p>
</blockquote>
<ul>
<li>Probabilidad teórica: (asume que los eventos simples son igualmente probables) los casos posibles sobre los casos totales</li>
</ul>
<p><span class="math display">\[P(A)= \frac{\text{Casos posibles}}{\text{Casos totales}}=\frac{\#A}{\# \Omega}\]</span></p>
<p>Ejemplo: El lanzamiento de un dado, <span class="math inline">\(\Omega=\{1,2,3,4,5,6\}\)</span>, si el evento es <span class="math inline">\(A=6\)</span>, <span class="math inline">\(B=PAR\)</span></p>
<p><span class="math inline">\(P(A)=\frac{1}{6}\)</span>, <span class="math inline">\(P(B)=\frac{3}{6}=1/2\)</span></p>
<ul>
<li>Probabilidad frecuentista:</li>
</ul>
<p><span class="math display">\[P(A)=lim_{n \rightarrow \infty} \frac{n(A)}{n} =lim_{n \rightarrow \infty} \frac{\# A_n}{n}\]</span></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tema-2-probabilidades.html#cb29-1"></a><span class="co">#0=cara, 1=escudo</span></span>
<span id="cb29-2"><a href="tema-2-probabilidades.html#cb29-2"></a><span class="kw">set.seed</span>(<span class="dv">999</span>)</span>
<span id="cb29-3"><a href="tema-2-probabilidades.html#cb29-3"></a>aux&lt;-<span class="kw">rbinom</span>(<span class="dv">1000</span>,<span class="dv">1</span>,<span class="fl">0.5</span>)</span>
<span id="cb29-4"><a href="tema-2-probabilidades.html#cb29-4"></a>aux</span></code></pre></div>
<pre><code>##    [1] 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 1 1 1 1 1 0
##   [31] 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 1
##   [61] 1 1 1 1 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0
##   [91] 1 0 0 1 1 0 1 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1
##  [121] 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0
##  [151] 1 1 1 1 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 0
##  [181] 1 0 1 1 0 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1
##  [211] 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0
##  [241] 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 1
##  [271] 1 1 0 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0
##  [301] 1 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1
##  [331] 1 0 1 0 1 0 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0
##  [361] 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0
##  [391] 1 0 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 0
##  [421] 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1
##  [451] 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 0
##  [481] 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 1
##  [511] 0 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1
##  [541] 1 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 1 1 0 1 0 0 0 1
##  [571] 1 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 0 0 1 1 0 1 1 0 1
##  [601] 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1
##  [631] 1 0 0 1 0 0 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 0 1 1 1 0 1
##  [661] 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0
##  [691] 0 1 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1
##  [721] 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 0
##  [751] 1 1 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1
##  [781] 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1
##  [811] 0 0 0 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 1 1 0 1 0
##  [841] 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0 1 0 0
##  [871] 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 0 1 0 1 1 0 1 0
##  [901] 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0
##  [931] 1 1 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 1 1
##  [961] 0 0 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0
##  [991] 0 0 1 1 1 0 1 0 1 1</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="tema-2-probabilidades.html#cb31-1"></a><span class="kw">sum</span>(aux)</span></code></pre></div>
<pre><code>## [1] 496</code></pre>
<p><span class="math inline">\(P(escudo)=\frac{496}{1000}=0.496\)</span></p>
<ul>
<li>Probabilidad subjetiva (experiencia) (apriori)</li>
</ul>
<p><span class="math display">\[P(escudo)=1/3\]</span></p>
<p><span class="math display">\[P(llueva_{hoy})=0.99\]</span></p>
<div id="probabilidad-de-un-evento" class="section level3">
<h3><span class="header-section-number">2.5.1</span> Probabilidad de un evento</h3>
<blockquote>
<p><strong>Definición:</strong> Una medida de probabilidad <span class="math inline">\(P\)</span> es una función, tal que:</p>
</blockquote>
<p><span class="math display">\[
P:\begin{array}
 &amp;&amp; \Sigma &amp;  \rightarrow &amp; [0,1]\\
 &amp; \downarrow &amp; &amp; \downarrow \\
 &amp; A &amp; \rightarrow &amp; P(A)
\end{array}
\]</span></p>
</div>
<div id="axíomas-básicos-de-la-probabilidad" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Axíomas básicos de la probabilidad</h3>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(P(A) \in [0,1]\)</span>, <span class="math inline">\(0 \leq P(A) \leq 1\)</span>, Para todo <span class="math inline">\(A\in \Sigma\)</span>, <span class="math inline">\(A\in\Omega\)</span></li>
<li><span class="math inline">\(P(\Omega)=1\)</span></li>
<li>Axioma aditividad finita, Si <span class="math inline">\(A_1,A_2, \ldots,A_n \in \Sigma\)</span>, Estos son eventos disjuntos 2 a 2 (mutuamente excluyentes). <span class="math inline">\(A_i \cap A_j=\emptyset\)</span> para todo <span class="math inline">\(i\neq j\)</span></li>
</ol>
<p><span class="math display">\[P(\cup_{i=1}^n{A_i})=\sum_{i=1}^n{P(A_i)}\]</span></p>
<p>Observación: Si <span class="math inline">\(A \cap B=\emptyset\)</span> entonces, <span class="math inline">\(P(A\cup B)=P(A)+P(B)\)</span></p>
<p>Ejemplo,</p>
<p>En el lanzamiento de un dado, sean los eventos, A=sale Par, B=Sale Impar. Calcular la probabilidad de <span class="math inline">\(P(A\cup B)\)</span>.</p>
<p><span class="math inline">\(A=\{2,4, 6\}\)</span>, <span class="math inline">\(B=\{1,3,5\}\)</span>, Notar que <span class="math inline">\(A \cap B= \emptyset\)</span>.</p>
<p>Por el axioma 2.
<span class="math display">\[P(A \cup B)=P(\Omega)=1\]</span>
Por el axioma 3.</p>
<p><span class="math display">\[P(A \cup B)=P(A)+P(B)=\frac{3}{6}+\frac{3}{6}=1\]</span></p>
</div>
<div id="propiedades" class="section level3">
<h3><span class="header-section-number">2.5.3</span> Propiedades</h3>
<ul>
<li><span class="math inline">\(P(\emptyset)=0\)</span></li>
</ul>
<p>Demostración: sea <span class="math inline">\(A\)</span> un evento,</p>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(A\cap \emptyset=\emptyset\)</span></li>
<li><span class="math inline">\(A=A\cup \emptyset\)</span></li>
</ol>
<p><span class="math display">\[P(A)=P(A\cup \emptyset)=P(A)+P(\emptyset)\]</span>
<span class="math display">\[P(A)=P(A)+P(\emptyset)\]</span>
<span class="math display">\[P(\emptyset)=0\]</span></p>
<ul>
<li><span class="math inline">\(P(A^c)=1-P(A)\)</span></li>
</ul>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(A\cap A^c=\emptyset\)</span>, entonces son eventos disjuntos</li>
<li><span class="math inline">\(A \cup A^c= \Omega\)</span>, entonces, <span class="math inline">\(P(A\cup A^c)=P(\Omega)=1\)</span> Ax2.</li>
</ol>
<p><span class="math display">\[1=P(\Omega)=P(A \cup A^c)=P(A)+P(A^c)\]</span></p>
<p>Así,</p>
<p><span class="math display">\[P(A^c)=1-P(A)\]</span></p>
<p>Ejercicios, demostrar:</p>
<ul>
<li><span class="math inline">\(P(A \cup B)=P(A)+P(B)-P(A\cap B)\)</span>, para cualesquiera eventos <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span></li>
</ul>
</div>
<div id="espacios-equiprobables" class="section level3">
<h3><span class="header-section-number">2.5.4</span> Espacios equiprobables</h3>
<p>Sea <span class="math inline">\(\Omega\)</span> un espacio muestral finito de tamaño <span class="math inline">\(n\)</span>,</p>
<p><span class="math display">\[\Omega=\{w_1,w_2,\ldots,w_n\}\]</span></p>
<blockquote>
<p>Definición: Es una función que asigna las mismas probabilidades a todos los resultados del espacio muestral, es decir, todos los eventos simples tienen la misma probabilidad de ocurrencia.</p>
</blockquote>
<p><span class="math display">\[P(w_1)=P(w_2)=\ldots=P(w_n)=\frac{1}{n}\]</span></p>
<p>Nota, tener en cuenta que <span class="math inline">\(w_i \cap w_j=\emptyset\)</span> para <span class="math inline">\(i\neq j\)</span> dado que los <span class="math inline">\(w_i\)</span> son eventos simples</p>
<p><span class="math display">\[P(w_1 \cup w_2\cup \ldots \cup w_n)=P(\Omega)=1\]</span></p>
<p><span class="math display">\[P(w_1 \cup w_2\cup \ldots \cup w_n)=P(w_1)+P(w_2)+\ldots+P(w_n)=1\]</span></p>
<p>Ejemplo, el lanzamiento de un dado legal genera un espacio muestral equiprobable. <span class="math inline">\(\Omega=\{1,2,3,4,5,6\}\)</span>, <span class="math inline">\(P(1)=P(2)=\ldots=P(6)=\frac{1}{6}\)</span></p>
<p>Ejemplo 1.</p>
<p>En un hipódromo 4 caballos, <span class="math inline">\(A\)</span>,<span class="math inline">\(B\)</span>,<span class="math inline">\(C\)</span> y <span class="math inline">\(D\)</span> compiten. Suponiendo que todos los caballos tienen la misma probabilidad de ganar (espacio equiprobable), calcular:</p>
<ol style="list-style-type: decimal">
<li>Probabilidad que gane el caballo <span class="math inline">\(A\)</span>.</li>
</ol>
<p>Resp. <span class="math inline">\(P(ganaA)=1/4\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Probabilidad que gane el caballo <span class="math inline">\(A\)</span> o el caballo <span class="math inline">\(D\)</span>.</li>
</ol>
<p>Resp. el evento de interés es <span class="math inline">\(ganaA \cup ganaD\)</span>, notar que <span class="math inline">\(ganarA \cap ganaD=\emptyset\)</span></p>
<p><span class="math display">\[P(ganaA\cup ganaD)=P(ganaA)+P(ganaD)=1/4+1/4=1/2\]</span></p>
<p>Ejemplo 2.</p>
<p>Tomemos ahora lo siguiente: <span class="math inline">\(A\)</span> tiene 2 veces más probabilidades de ganar que <span class="math inline">\(B\)</span>; <span class="math inline">\(B\)</span> tiene 2 veces más probabilidad de ganar que <span class="math inline">\(C\)</span> y <span class="math inline">\(C\)</span> tiene 2 veces más probabilidades de ganar que <span class="math inline">\(D\)</span>. (espacio no equiprobable)</p>
<ol style="list-style-type: decimal">
<li>Probabilidad que gane el caballo <span class="math inline">\(A\)</span></li>
<li>Probabilidad que gane el caballo <span class="math inline">\(A\)</span> o el caballo <span class="math inline">\(D\)</span>.</li>
</ol>
<p>Sean los eventos simples, <span class="math inline">\(w_1=gA=GanaA\)</span>, <span class="math inline">\(w_2=gB=GanaB\)</span>, <span class="math inline">\(w_3=gC=GanaC\)</span> y <span class="math inline">\(w_4=gD=GanaD\)</span></p>
<p>Sabemos que: <span class="math inline">\(P(gA)=2*P(gB)=2*2*P(gC)=2*2*2*P(gD)=8*P(gD)\)</span></p>
<p><span class="math display">\[P(gA)+P(gB)+P(gC)+P(gD)=1\]</span></p>
<p><span class="math display">\[8*P(gD)+4*P(gD)+2*P(gD)+P(gD)=1\]</span></p>
<p><span class="math display">\[P(gD)(8+4+2+1)=1\]</span>
<span class="math display">\[P(gD)=\frac{1}{15}\]</span></p>
<p>Asi, <span class="math inline">\(P(gD)=1/15\)</span>, <span class="math inline">\(P(gC)=2/15\)</span>, <span class="math inline">\(P(gB)=4/15\)</span>, <span class="math inline">\(P(gA)=8/15\)</span></p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(P(gA)=8/15\)</span></li>
<li><span class="math inline">\(P(gA\cup gD)=P(gA)+P(gD)=8/15+1/15=9/15\)</span></li>
</ol>
<p>Ejemplo. Se lanza un par de dados legales simultaneamente, encontrar las probabilidades:</p>
<ol style="list-style-type: lower-alpha">
<li>La suma sea menor que 4</li>
<li>La suma sea 9</li>
<li>El resultado del primer dado sea mayor que el segundo</li>
</ol>
<p><span class="math inline">\(\#\Omega=36\)</span>, <span class="math inline">\(P(d1=i,d2=j)=1/36\)</span> para <span class="math inline">\(i,j=1:6\)</span></p>
<ol style="list-style-type: lower-alpha">
<li><p>Resp.
<span class="math display">\[P((1,1)\cup (1,2)\cup (2,1))=P(1,1)+P(1,2)+P(2,1)=1/36+1/36,1/36=3/36=1/12\]</span></p></li>
<li><p>Resp.</p></li>
</ol>
<p><span class="math display">\[P(suma=9)=\frac{4}{36}\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Resp.</li>
</ol>
<p><span class="math display">\[P(d1&gt;d2)=\frac{15}{36}=\frac{5}{12}\]</span></p>
<ul>
<li><p>Ejercicio (7, pg243). Un lote continene 10 piezas buenas, 4 con defectos menores y 2 con defectos mayores. Se extraen 2 piezas al azar. Calcular:</p>
<pre><code>  1. Calcular el tamaño del espacio muestral $\#\Omega=\binom{16}{2}=120$
  2. Probabilidad que ambas sean perfectas </code></pre></li>
</ul>
<p><span class="math display">\[P(2perf)=\frac{\binom{10}{2}}{\binom{16}{2}}=\frac{45}{120}=\frac{15}{40}=\frac{3}{8}\]</span></p>
<pre><code>    3. Probabilidad que por lo menos una sea perfecta
    </code></pre>
<p><span class="math display">\[P(1perf \cup 2perf)=P(1perf)+P(2perf)=\frac{\binom{10}{1}\binom{6}{1}}{\binom{16}{2}}+\frac{3}{8}=\frac{60}{120}+\frac{3}{8}=\frac{1}{2}+\frac{3}{8}=\frac{7}{8}\]</span></p>
<pre><code>    4. Probabilidad que ninguna tenga un defecto mayorjihj
    5. Probabilidad que ninguna sea perfecta
    </code></pre>
<ul>
<li>Ejercicio (14, pg-244). Sea un dado, tal que la probabilidad de las distintas caras es proporcional al número de puntos inscritos en ellos. Hallar la probabilidad de obtener con este dado, un número par.</li>
</ul>
<p><span class="math display">\[\Omega=\{1,2,3,4,5,6\}\]</span></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tema-2-probabilidades.html#cb36-1"></a><span class="co">#relativar </span></span>
<span id="cb36-2"><a href="tema-2-probabilidades.html#cb36-2"></a>px&lt;-(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)<span class="op">/</span><span class="kw">sum</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</span>
<span id="cb36-3"><a href="tema-2-probabilidades.html#cb36-3"></a><span class="kw">sum</span>(px[<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>)])</span></code></pre></div>
<pre><code>## [1] 0.5714286</code></pre>
<p><span class="math display">\[P(2,4,6)=P(2 \cup 4 \cup 6 )=P(2)+P(4)+P(6)=0.095+0.19+0.286=0.571\]</span></p>
<ul>
<li>Ejercicio (11, pg-244). Sea <span class="math inline">\(\Omega=\{x \in Z/ 1 \leq x \leq 200 \}\)</span>, donde <span class="math inline">\(Z\)</span> es el conjunto de los números enteros. Encuentre las probabilidades de los siguiente eventos.
+ <span class="math inline">\(A=\{x \in \Omega / x \text{ es divisible por }7 \}\)</span>
+ <span class="math inline">\(B=\{x \in \Omega / x=3n+10, n\in Z^+ \}\)</span>
+ <span class="math inline">\(C=\{x \in \Omega / x^2+1\leq 375 \}\)</span></li>
</ul>
<p>Para <span class="math inline">\(P(A)\)</span></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tema-2-probabilidades.html#cb38-1"></a><span class="kw">sum</span>((<span class="dv">1</span><span class="op">:</span><span class="dv">200</span> <span class="op">%%</span><span class="st"> </span><span class="dv">7</span>)<span class="op">==</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 28</code></pre>
<p><span class="math display">\[P(A)=\frac{\# A}{\# \Omega}=\frac{28}{200}=0.14\]</span></p>
<p>Para <span class="math inline">\(P(B)\)</span></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tema-2-probabilidades.html#cb40-1"></a>n&lt;-<span class="dv">1</span><span class="op">:</span><span class="dv">100</span></span>
<span id="cb40-2"><a href="tema-2-probabilidades.html#cb40-2"></a><span class="kw">sum</span>((<span class="dv">3</span><span class="op">*</span>n<span class="op">+</span><span class="dv">10</span>)<span class="op">&lt;=</span><span class="dv">200</span>)</span></code></pre></div>
<pre><code>## [1] 63</code></pre>
<p><span class="math display">\[P(B)=\frac{\# B}{\# \Omega}=\frac{63}{200}=0.315\]</span></p>
<p><span class="math display">\[P(C)=\frac{\# C}{\# \Omega}=\frac{19}{200}=0.095\]</span></p>
</div>
</div>
<div id="probabilidad-condicional" class="section level2">
<h2><span class="header-section-number">2.6</span> Probabilidad Condicional</h2>
<ul>
<li>Evaluamos dos eventos o más</li>
<li>Conocer como se altera o cambia la probabilidad de un evento a partir de la ocurrencia de otro</li>
</ul>
<p>Ejemplo con las notas de una materia.</p>
<p>Sea el experimento la nota de que obtiene un estudiante al inscribirse en una materia. Sea el evento A: el estudiante aprueba la materia. ¿Cuál es el probabilidad de A (suponiendo un espacio muestral equiprobable)?</p>
<ul>
<li><span class="math inline">\(\Omega=\{0,1,2,\ldots,100 \}\)</span>, <span class="math inline">\(\# \Omega= 101\)</span>, <span class="math inline">\(P(i)=\frac{1}{101}\)</span></li>
<li><span class="math inline">\(P(A)=P(51\cup 52 \cup \ldots \cup 100)=P(51)+P(52)+\ldots+P(100)=\frac{50}{101}=0.495\)</span></li>
<li><span class="math inline">\(P(A^c)=1-P(A)=1-\frac{50}{101}=\frac{51}{101}=0.505\)</span></li>
</ul>
<p>Sea el evento B= el estudiante dio 2 parciales cada uno con un valor de 30, obteniendo el estudiante una nota sumada de los 2 de 27 puntos. ¿Cuál sera ahora la probabilidad de que el estudiante apruebe la materia?</p>
<p>Podemos notar que la ocurrencia de <span class="math inline">\(B\)</span> esta alterando el experimento y por ende la probabilidad de aprobar. Pensando en esto, ¿cómo se altera el espacio muestral?</p>
<ul>
<li><span class="math inline">\(\Omega_{ocurrioB}=\{27,28,29,\ldots, 67\}\)</span>, <span class="math inline">\(\#Omega=41\)</span></li>
<li><span class="math inline">\(P(A/B)=\frac{17}{41}=0.415\)</span></li>
</ul>
<p>Ejemplos.</p>
<ul>
<li>¿Cuál es la probabilidad de aprobar la materia X dado que se tiene una nota de 20/30 en el primer parcial?</li>
<li>Se lanza una moneda y después se lanza un dado , ¿Cuál es la probabilidad de obtener un 5 en el dado, si salió cara en la moneda?</li>
<li>Una urna contiene 3 bolas rojas y 3 bolas blancas, se realiza una selección de 2 bolas de manera consecutiva y sin reemplazo ¿Cuál es la probabilidad de que la segunda bola sea roja, sabiendo que la primera bola fue blanca?</li>
</ul>
<blockquote>
<p>Definición: Sean dos eventos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>, tal que <span class="math inline">\(P(B)&gt;0\)</span>, la probabilidad condicional de que ocurra el evento <span class="math inline">\(A\)</span>, dado que ha ocurrido el evento <span class="math inline">\(B\)</span>, se define por:</p>
</blockquote>
<p><span class="math display">\[P(A/B)=\frac{P(A \cap B)}{P(B)}\]</span></p>
<p>Nota: Cualquier condición que se de entre las probabilidades, afecta directamente el espacio muestral, esto depende de la relación entre los eventos.</p>
<p>Ejemplo:</p>
<p>En la carrera de Informática van a existir elecciones para el director de carrera, existen 3 frentes y estos son <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span>, la carrera esta compuesta por 3 grupos de estudiantes, los políticos, los académicos y el resto, la estructura de votación según un sondeo aleatorio a 200 estudiantes es:</p>
<ul>
<li>Los políticos (50), 20 votan por A, 20 votan por B y 10 votan por C</li>
<li>Los académicos que son 40, 10 votan por A, 10 votan por B y 20 votan por C</li>
<li>El resto (110), 30 votan por A, 50 votan por B y el resto vota por C</li>
</ul>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tema-2-probabilidades.html#cb42-1"></a>A&lt;-<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">20</span>,<span class="dv">10</span>),<span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">20</span>),<span class="kw">c</span>(<span class="dv">30</span>,<span class="dv">50</span>,<span class="dv">30</span>))</span>
<span id="cb42-2"><a href="tema-2-probabilidades.html#cb42-2"></a><span class="kw">colnames</span>(A)&lt;-<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;C&quot;</span>)</span>
<span id="cb42-3"><a href="tema-2-probabilidades.html#cb42-3"></a><span class="kw">rownames</span>(A)&lt;-<span class="kw">c</span>(<span class="st">&quot;POL&quot;</span>,<span class="st">&quot;ACA&quot;</span>,<span class="st">&quot;RES&quot;</span>)</span>
<span id="cb42-4"><a href="tema-2-probabilidades.html#cb42-4"></a>knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">addmargins</span>(A))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">A</th>
<th align="right">B</th>
<th align="right">C</th>
<th align="right">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">POL</td>
<td align="right">20</td>
<td align="right">20</td>
<td align="right">10</td>
<td align="right">50</td>
</tr>
<tr class="even">
<td align="left">ACA</td>
<td align="right">10</td>
<td align="right">10</td>
<td align="right">20</td>
<td align="right">40</td>
</tr>
<tr class="odd">
<td align="left">RES</td>
<td align="right">30</td>
<td align="right">50</td>
<td align="right">30</td>
<td align="right">110</td>
</tr>
<tr class="even">
<td align="left">Sum</td>
<td align="right">60</td>
<td align="right">80</td>
<td align="right">60</td>
<td align="right">200</td>
</tr>
</tbody>
</table>
<p>Encuentre</p>
<ul>
<li>¿Cuál es la probabilidad de que un estudiante académico vote por C?</li>
</ul>
<p><span class="math display">\[P(\text{vote C}/academico)=\frac{P(\text{vote C} \cap academico)}{P(academico)}=\frac{\frac{20}{200}}{\frac{40}{200}}=\frac{20}{40}=0.5\]</span></p>
<ul>
<li>¿Cuál es la probabilidad de que un estudiante político vote por A?</li>
</ul>
<p><span class="math display">\[P(\text{vote A}/politico)=\frac{20}{50}=0.4\]</span></p>
<ul>
<li>¿Cuál es la probabilidad de que gane el candidato B en estudiantes?</li>
</ul>
<p><span class="math display">\[P(\text{gane B})=\frac{80}{200}=0.4\]</span></p>
<ul>
<li>¿Cuál es la probabilidad que un estudiante seleccionado al azar sea académico dado que votara por el candidato A?</li>
</ul>
<p><span class="math display">\[P(academico/\text{vote A})=\frac{10}{60}=\frac{1}{6}\]</span></p>
<p>Ejercicios:</p>
<ol style="list-style-type: decimal">
<li>¿Cuál es la probabilidad de aprobar la materia <span class="math inline">\(X\)</span> dado que se tiene una nota de 20/30 en el primer parcial?</li>
<li>Se lanza una moneda y después se lanza un dado , ¿Cuál es la probabilidad de obtener un 5 en el dado, si salió cara en la moneda?</li>
</ol>
<p>Solución,</p>
<p>Sean los eventos C: Sale cara en la moneda, S: Sale sello en la moneda, y los eventos D1, D2, … , D6 sale el número en el dado.</p>
<p><span class="math display">\[P(D5/C)=\frac{P(D5 \cap  C)}{P(C)}=\frac{\frac{1}{12}}{\frac{6}{12}}=\frac{1}{6}\]</span>
Notar algo: <span class="math inline">\(P(D5)=\frac{1}{6}=P(D5/C)=P(D5/S)\)</span>. Si la condición no afecta la probabilidad del evento que busca calcular, podemos afirmar que los eventos son independientes.</p>
<p>La ocurrencia de un evento, no altera a otro, a eso le llamamos independencia.</p>
<p>Si los eventos A y B son independientes, entonces:</p>
<p><span class="math display">\[P(A \cap B)= P(A)*P(B)\]</span>
<span class="math display">\[P(A/B)=\frac{P(A\cap B)}{P(B)}=\frac{P(A) P(B)}{P(B)}=P(A)\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Una urna contiene 3 bolas rojas y 3 bolas blancas, se realiza una selección de 2 bolas de manera consecutiva y sin reemplazo ¿Cuál es la probabilidad de que la segunda bola sea roja, sabiendo que la primera bola fue blanca?</li>
</ol>
<p>Solución, <span class="math inline">\(P(R/B)=3/5\)</span></p>
<p><strong>Ejemplo</strong></p>
<p>Se tiene la tabla de admisión de 356 estudiantes de la UMSA, de acuerdo a la carrera y su municipio de procedencia</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="tema-2-probabilidades.html#cb43-1"></a>A&lt;-<span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">20</span>),<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">60</span>,<span class="dv">50</span>,<span class="dv">10</span>),<span class="kw">c</span>(<span class="dv">5</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb43-2"><a href="tema-2-probabilidades.html#cb43-2"></a><span class="kw">colnames</span>(A)&lt;-<span class="kw">c</span>(<span class="st">&quot;ING&quot;</span>,<span class="st">&quot;ECO&quot;</span>,<span class="st">&quot;INF&quot;</span>,<span class="st">&quot;DER&quot;</span>)</span>
<span id="cb43-3"><a href="tema-2-probabilidades.html#cb43-3"></a><span class="kw">rownames</span>(A)&lt;-<span class="kw">c</span>(<span class="st">&quot;LAPAZ&quot;</span>,<span class="st">&quot;ELALTO&quot;</span>,<span class="st">&quot;VIACHA&quot;</span>)</span>
<span id="cb43-4"><a href="tema-2-probabilidades.html#cb43-4"></a>knitr<span class="op">::</span><span class="kw">kable</span>(<span class="kw">addmargins</span>(A))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">ING</th>
<th align="right">ECO</th>
<th align="right">INF</th>
<th align="right">DER</th>
<th align="right">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">LAPAZ</td>
<td align="right">100</td>
<td align="right">40</td>
<td align="right">50</td>
<td align="right">20</td>
<td align="right">210</td>
</tr>
<tr class="even">
<td align="left">ELALTO</td>
<td align="right">20</td>
<td align="right">60</td>
<td align="right">50</td>
<td align="right">10</td>
<td align="right">140</td>
</tr>
<tr class="odd">
<td align="left">VIACHA</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="left">Sum</td>
<td align="right">125</td>
<td align="right">100</td>
<td align="right">101</td>
<td align="right">30</td>
<td align="right">356</td>
</tr>
</tbody>
</table>
<p>Sea el experimento seleccionar a un estudiante al azar del grupo de 356.</p>
<ul>
<li>¿Cuál es la probabilidad que el estudiantes sea de la carrera de economía, sabiendo que vive en El Alto?</li>
</ul>
<p><span class="math display">\[P(ECO/ELALTO)=\frac{60}{140}\]</span></p>
<ul>
<li>¿Cuál es la probabilidad que el estudiantes sea de la carrera de informática, sabiendo que vive en La Paz?</li>
</ul>
<p><span class="math display">\[P(INF/LAPAZ)=\frac{50}{210}\]</span></p>
<ul>
<li>¿Cuál es la probabilidad que el estudiantes sea de Viacha, sabiendo que esta en la carrera de ingenieria?</li>
</ul>
<p><span class="math display">\[P(VIACHA/ING)=\frac{5}{125}\]</span></p>
<ul>
<li>¿Cuál es la probabilidad que el estudiantes sea de Viacha ó de La Paz, sabiendo que esta en la carrera de ingenieria.?</li>
</ul>
<p><span class="math display">\[P(VIACHA\cup LAPAZ  /ING)=\frac{P((VIACHA\cup LAPAZ)\cap ING)}{P(ING)}=\frac{P((VIACHA\cap ING)\cup (LAPAZ\cap ING))}{P(ING)}\]</span></p>
<p><span class="math display">\[P(VIACHA\cup LAPAZ  /ING)=\frac{P(VIACHA\cap ING)+P(LAPAZ\cap ING)}{P(ING)}\]</span>
<span class="math display">\[P(VIACHA\cup LAPAZ  /ING)=P(VIACHA/ING)+P(LAPAZ/ING)=5/125+100/125=\frac{105}{125}\]</span></p>
<p>Por el principio de que Viacha y La Paz son eventos mutuamente excluyentes (axioma 3)</p>
<div id="regla-de-la-multiplicación" class="section level3">
<h3><span class="header-section-number">2.6.1</span> Regla de la multiplicación</h3>
<p><span class="math display">\[P(A/B)=\frac{P(A\cap B)}{P(B)}\]</span></p>
<p><span class="math display">\[P(B/A)=\frac{P(B\cap A)}{P(A)}\]</span></p>
<p><span class="math display">\[P(A \cap B)=P(B)P(A/B)=P(A)P(B/A)\]</span></p>
<blockquote>
<p>Teorema: La regla de la multiplicación</p>
</blockquote>
<p>Sean <span class="math inline">\(A_1,A_2,\ldots,A_k\)</span> eventos, de tal forma que:</p>
<p><span class="math display">\[P(A_1\cap A_2 \cap \ldots \cap A_{k-1})&gt;0\]</span></p>
<p>Entonces:</p>
<p><span class="math display">\[P(A_1\cap A_2 \cap \ldots \cap A_{k})=P(A_1)P(A_2/A_1)P(A_3/A_1\cap A_2)\ldots P(A_k/A_1 \cap A_2 \cap \ldots A_{k-1}) \]</span></p>
<p>Ejemplo 1, demostrar:</p>
<p><span class="math display">\[P(A \cap B \cap C)=P(A)P(B/A)P(C/A\cap B)\]</span>
<span class="math display">\[P(A)P(B/A)P(C/A\cap B)=P(A)*\frac{P(A \cap B)}{P(A)}*\frac{P(C\cap A \cap B)}{P(A \cap B)}=P(A \cap B \cap C)\]</span></p>
</div>
<div id="independencia-de-eventos" class="section level3">
<h3><span class="header-section-number">2.6.2</span> Independencia de Eventos</h3>
<blockquote>
<p>Definición: Sean los eventos A y B, estos son independientes si la ocurrencia de A no interfiere la ocurrencia de B y viceversa.</p>
</blockquote>
<p>Si A y B son independientes,</p>
<p><span class="math display">\[P(A\cap B)=P(A)*P(B)\]</span></p>
<p>Ejemplo. Se lanza una moneda y después se lanza un dado , ¿Cuál es la probabilidad de obtener un 5 en el dado, si salió cara en la moneda?</p>
<p><span class="math display">\[P(D=5/C)=\frac{P(D=5 \cap C)}{P(C)}=\frac{P(D=5)P(C)}{P(C)}=P(D=5)=1/6\]</span></p>
<p>Nota: Si A y B son independientes, entonces:</p>
<p><span class="math display">\[P(A/B)=P(A)\]</span>
<span class="math display">\[P(B/A)=P(B)\]</span></p>
<p>Ejemplos,</p>
<ol style="list-style-type: decimal">
<li>Dado que <span class="math inline">\(P(A)=1/2\)</span>, <span class="math inline">\(P(B)=1/3\)</span>, <span class="math inline">\(P(A\cap B)=1/4\)</span></li>
</ol>
<ul>
<li><span class="math inline">\(P(A \cup B)=P(A)+P(B)-P(A\cap B)=1/2+1/3-1/4=7/12\)</span></li>
<li><span class="math inline">\(P(A/B)=\frac{P(A \cap B)}{P(B)}=\frac{1/4}{1/3}=3/4\)</span></li>
<li><span class="math inline">\(P(B/A)=\frac{P(B\cap A)}{P(A)}=\frac{1/4}{1/2}=1/2\)</span></li>
<li><span class="math inline">\(P(B^C/A^C)=\frac{P(B^C\cap A^c)}{P(A^c)}=\frac{P((A\cup B)^c)}{1-P(A)}=\frac{1-P(A\cup B)}{1-P(A)}=\frac{1-7/12}{1-1/2}=5/6\)</span></li>
</ul>
<p>Ejercicio (5, pg 287). Un restaurante ofrece dos tipos de comida, ensalada o plato de carne. 20% de los clientes hombres prefieren la ensalada, 30% de las mujeres escogen carne, el 75% de los clientes son hombres. Considere los siguientes eventos.</p>
<ul>
<li>H: es hombre, M: es mujer, E: prefiere la ensalda, C: Prefiere Carne.</li>
</ul>
<p>Se pide calcular:</p>
<ul>
<li><span class="math inline">\(P(E/H)\)</span>, <span class="math inline">\(P(C/M)\)</span></li>
<li><span class="math inline">\(P(E \cap H)\)</span>, <span class="math inline">\(P(C \cap M)\)</span></li>
<li><span class="math inline">\(P(M/E)\)</span></li>
</ul>
<p>Tarea 2: Resolver el ejercicio 6 de la página 287 del libro.
Tarea 3: Leer del libro el desde el apartado 5.6.3 (Teorema de la probabilidad total y el teorema de bayes) hasta la página 267.</p>
</div>
</div>
<div id="teorema-de-la-probabilidad-total" class="section level2">
<h2><span class="header-section-number">2.7</span> Teorema de la Probabilidad Total</h2>
<div class="figure">
<img src="https://4.bp.blogspot.com/-8lzibwRArUw/WJV3xFSHJaI/AAAAAAAAgZM/28mWy8iAm0MKfxJYbDhqVL6iGqXSbJA-QCLcB/s1600/%25E8%259E%25A2%25E5%25B9%2595%25E5%25BF%25AB%25E7%2585%25A7%2B2017-02-04%2B%25E4%25B8%258B%25E5%258D%25882.41.58.png" alt="" />
<p class="caption">Probabilidad Total</p>
</div>
<p>Sea <span class="math inline">\(A_1,A_2,\ldots ,A_n\)</span> un partición del espacio muestral, de tal forma que: <span class="math inline">\(P(A_i)&gt;0\)</span> para todo <span class="math inline">\(i=1, \ldots,n\)</span>. La partición representa que <span class="math inline">\(U_{i=1}^n A_i=\Omega\)</span> y <span class="math inline">\(A_i \cap A_j =\emptyset\)</span> para todo <span class="math inline">\(i\neq j\)</span>. Para cualquier evento <span class="math inline">\(B \in \Omega\)</span>.</p>
<p><span class="math display">\[P(B)=\sum_{i=1}^n{P(A_i \cap B)}=\sum_{i=1}^n{P(A_i)P(B/A_i )}\]</span></p>
<p>Ejemplo: Suponer que la población del departamento de la Paz esta conformado por 55% de mujeres y 45 % de hombres. Supongamos que el 30% de los hombres y el 20% de las mujeres fuman. Determinar la probabilidad de que una persona fume en el departamento de La Paz.</p>
<p>Solución: Sean los eventos:</p>
<ul>
<li>H: es hombre (<span class="math inline">\(M^c\)</span>)</li>
<li>M: es mujer (<span class="math inline">\(H^c\)</span>)</li>
<li>F: Fuma</li>
<li><span class="math inline">\(F^c\)</span>: No fuma</li>
</ul>
<p>Además, <span class="math inline">\(P(M)=0.55\)</span>, <span class="math inline">\(P(H)=P(M^C)=0.45\)</span>, <span class="math inline">\(P(F/H)=0.3\)</span> y <span class="math inline">\(P(F/M)=0.2\)</span>, <span class="math inline">\(P(F)=?\)</span>.</p>
<p><span class="math display">\[P(F)=P(H)P(F/H)+P(M)P(F/M)=0.45*0.3+0.55*0.2=0.245\]</span></p>
<p>¿Cuál es la probabilidad de no fumar en esta población?</p>
<p><span class="math inline">\(P(F^c)=1-P(F)=1-0.245=0.755\)</span></p>
<p>Ejercicio,</p>
<p>Para la elección del gobernador en el departamento de La Paz, se realizó una encuesta en 3 dominios de estudio: Municipio de La Paz, El Alto y el resto de los municipios, se sabe que La Paz ocupa el 35% de votantes, El Alto el 40% y los demás el resto de municipios. Los resultados por dominio respecto el apoyo al candidato “Z” es el siguiente:</p>
<ul>
<li>La Paz: 39%</li>
<li>El Alto: 49%</li>
<li>Resto: 65%</li>
</ul>
<p>Según la encuesta, ¿cuál es la probabilidad que el candidato Z sea gobernador?</p>
<p>Solución, Sea la partición LP: La Paz, EA: El Alto, R: el resto, y el evento Z: Apoyo al candidato Z. Se pide <span class="math inline">\(P(Z)\)</span>.</p>
<p>Como información, tenemos <span class="math inline">\(P(LP)=0.35\)</span>, <span class="math inline">\(P(EA)=0.4\)</span>, <span class="math inline">\(P(R)=0.25\)</span>, <span class="math inline">\(P(Z/LP)=0.39\)</span>, <span class="math inline">\(P(Z/EA)=0.49\)</span> y <span class="math inline">\(P(Z/R)=0.65\)</span>. Así,</p>
<p><span class="math display">\[P(Z)=P(LP)*P(Z/LP)+P(EA)*P(Z/EA)+P(R)*P(Z/R)=0.35*0.39+0.4*0.49+0.25*0.65=0.495\]</span></p>
</div>
<div id="teorema-de-bayes" class="section level2">
<h2><span class="header-section-number">2.8</span> Teorema de Bayes</h2>
<p>Sea <span class="math inline">\(A_1,A_2,\ldots ,A_n\)</span> un partición del espacio muestral, de tal forma que: <span class="math inline">\(P(A_i)&gt;0\)</span> para todo <span class="math inline">\(i=1, \ldots,n\)</span>. Sea <span class="math inline">\(B \in \Omega\)</span> un evento tal que todas las <span class="math inline">\(P(B/A_i)\)</span> son conocidas. Entonces para cada <span class="math inline">\(A_i\)</span> tenemos:</p>
<p><span class="math display">\[P(A_i/B)=\frac{P(A_i)P(B/A_i)}{\sum_{j=1}^n{P(A_j)P(B/A_j )}}\]</span></p>
<p>Demostración,</p>
<p><span class="math display">\[P(A_i/B)=\frac{P(A_i \cap B)}{P(B)}=\frac{P(A_i)*P(B/A_i)}{\sum_{j=1}^n{P(B\cap A_j)}}=\frac{P(A_i)*P(B/A_i)}{\sum_{j=1}^n{P(A_j)P(B/A_j)}}\]</span></p>
<p>Dentro del teorema de Bayes, se conoce a <span class="math inline">\(P(A_i)\)</span> como probabilidades a priori, a <span class="math inline">\(P(B/A_i)\)</span> se llama la verosimilitud (información), finalmente a <span class="math inline">\(P(A_i/B)\)</span> se le llama probabilidad a posteriori.</p>
<p>Forma simple:</p>
<p><span class="math display">\[P(A/B)=\frac{P(A)P(B/A)}{P(B)}\]</span></p>
<p>Demostración,</p>
<p><span class="math display">\[P(A/B)=\frac{P(A\cap B)}{P(B)}=\frac{P(A)P(B/A)}{P(B)}\]</span></p>
<p>Ejemplo: Un análisis de sangre de laboratorio es <span class="math inline">\(95\)</span> por ciento efectivo en la detección de una determinada enfermedad, cuando de hecho está presente. Sin embargo, la prueba también arroja un resultado “falso positivo” para el 1 por ciento de las personas sanas evaluadas. (Es decir, si se evalúa a una persona sana, entonces, con una probabilidad de <span class="math inline">\(0.01\)</span>, el resultado de la prueba implicará que él o ella tiene la enfermedad). Si el <span class="math inline">\(0.5\)</span> por ciento de la población realmente tiene la enfermedad, ¿cuál es la probabilidad de que una persona tenga la enfermedad dado que el resultado de la prueba es positivo?</p>
<p>Solución: vamos a identificar los siguientes eventos:</p>
<ul>
<li>E: Se tiene la enfermedad</li>
<li><span class="math inline">\(E^c\)</span>: No se tiene la enfermedad</li>
<li>T+: La prueba da positiva a la enfermedad</li>
<li>T-: La prueba da negativa a la enfermedad</li>
</ul>
<p>Como dato tenemos: <span class="math inline">\(P(E)=0.5/100=0.005\)</span>, <span class="math inline">\(P(E^c)=1-P(E)=0.995\)</span>, tener o no la enfermedad es la partición dentro del problema. <span class="math inline">\(P(T+/E)=0.95\)</span>, <span class="math inline">\(P(T+/E^C)=0.01\)</span>. <span class="math inline">\(P(E/T+)=¿?\)</span>.</p>
<p><span class="math display">\[P(E/T+)=\frac{P(E \cap T+)}{P(T+)}=\frac{P(E)P(T+/E)}{P(E)P(T+/E)+P(E^C)P(T+/E^C)}\]</span></p>
<p><span class="math display">\[P(E/T+)=\frac{0.005*0.95}{0.005*0.95+0.995*0.01}=0.3231\]</span></p>
<p>El 32.31% de los pacientes que son diagnosticados con la enfermedad en realidad si están enfermos.</p>
<p>Calcular: <span class="math inline">\(P(T-/E^c)\)</span>, <span class="math inline">\(P(E/T-)\)</span></p>
<p><span class="math display">\[P(T-/E^c)=0.99\]</span>
<span class="math display">\[P(E/T-)=0,000253\]</span></p>
</div>
<div id="ejercicios." class="section level2">
<h2><span class="header-section-number">2.9</span> Ejercicios.</h2>
<ul>
<li>(Pg, 290. Ej: 22). Una de cada 10 personas de una población tiene tuberculosis. De las personas que tienen tuberculosis, el 80% reacciona positivamente a la prueba Y, mientras que el 30% de los que no tienen tuberculosis reaccionan positivamente. Una persona de la población es seleccionada aleatoriamente y la prueba Y es aplicada. ¿Cuál es la probabilidad de que esa persona tenga tuberculosis, si reacciono positivamente a la prueba?</li>
</ul>
<p>Solución, sean los siguientes eventos:</p>
<ul>
<li><span class="math inline">\(Y+\)</span> La prueba da positivo a Tuberculosis</li>
<li><span class="math inline">\(Y-\)</span> La prueba da negativo a Tuberculosis</li>
<li><span class="math inline">\(T\)</span> La persona tiene tuberculosis</li>
<li><span class="math inline">\(T^c\)</span> La persona no tiene tuberculosis</li>
</ul>
<p>La información dada es: <span class="math inline">\(P(T)=0.1\)</span>, <span class="math inline">\(P(T^c)=0.9\)</span>, <span class="math inline">\(P(Y+/T)=0.8\)</span>, <span class="math inline">\(P(Y+/T^C)=0.3\)</span>, <span class="math inline">\(P(T/Y+)=?\)</span></p>
<p><span class="math display">\[P(T/Y+)=\frac{P(T)P(Y+/T)}{P(Y+)}=\frac{P(T)P(Y+/T)}{P(T)*P(Y+/T)+P(T^C)*P(Y+/T^C)}\]</span></p>
<p><span class="math display">\[P(T/Y+)=\frac{0.1*0.8}{0.1*0.8+0.9*0.3}=\frac{0.08}{0.35}=0.2286\]</span></p>
<p>Repasar, Monty Hall</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tema-1-estadística-descriptiva.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tema-3-variables-aleatorias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
